spring:
  application:
    name: usuarios-service
  profiles:
    active: default
  config:
    import: "optional:configserver:http://config-server:8888"

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
    healthcheck:
      enabled: true