spring:
  application:
    name: ordenes-service
  config:
    import: "optional:configserver:http://config-server:8888"
  # AÃ±ade esto como respaldo obligatorio
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/