spring:
  application:
    name: ordenes-service
  config:
    import: "optional:configserver:http://config-server:8888/"
  cloud:
    # --- AGREGA ESTO AQU√ç ---
    config:
      fail-fast: true
    # -------------------------
    function:
      definition: consumirRespuestaPago
    stream:
      bindings:
        ordenes-topic-out-0:
          destination: ordenes-topic
        consumirRespuestaPago-in-0:
          destination: pagos-topic
          group: ordenes-group