spring:
  application:
    name: pagos-service
  config:
    import: "optional:configserver:http://config-server:8888/"

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    prefer-ip-address: true